- name: Enable copr repo
  community.general.copr:
    state: enabled
    name: "{{ item.repo }}"
  loop: "{{ copr }}"

- name: Install Package
  ansible.builtin.package:
    name: "{{ item.pkg }}"
    state: present
  loop: "{{ copr }}"
