- name: Install ZSH Base Packages
  ansible.builtin.package:
    name:
      - git
      - zsh

- name: Get Logged in User
  ansible.builtin.set_fact:
    ansible_user: "{{ ansible_env.SUDO_USER if ansible_env.SUDO_USER is defined else ansible_user_id }}"

- name: Check if oh-my-zsh is Already Installed
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/.oh-my-zsh"
  register: zsh_folder

- name: Install oh-my-zsh
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell:
    cmd: 'curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash'
  when: not zsh_folder.stat.exists

- name: Download powerlevel10k
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Download zsh-autosuggestions
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Download zsh-highlighting
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Copy ZSH Config to Remote
  ansible.builtin.template:
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    src: ./templates/my_zshrc.j2
    dest: "/home/{{ ansible_user }}/.zshrc"

- name: Copy p10k Config to Remote
  ansible.builtin.copy:
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    src: ./files/.p10k.zsh
    dest: "/home/{{ ansible_user }}/.p10k.zsh"

- name: Set SSH User Shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
